/** Observations from actual Host tool results; never an automatic acceptance verdict. */
export function nativeToolObservations(nodes: readonly unknown[]) {
  const records: { eventSeq: number; callId: string; tool: string; kind: 'image' | 'http'; detail: string }[] = []
  const object = (value: unknown): Record<string, unknown> | undefined => value !== null && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : undefined
  for (const raw of nodes) {
    const node = object(raw)
    const call = object(node?.call)
    if (node?.kind !== 'tool-result' || node.isError !== false || node.error !== undefined || typeof node.callId !== 'string'
      || !Number.isSafeInteger(node.seq) || Number(node.seq) < 0 || typeof call?.name !== 'string') continue
    const identity = { eventSeq: Number(node.seq), callId: node.callId, tool: call.name }
    const meta = object(node.meta)
    // Match the native web_fetch result metadata contract, not arbitrary text claiming HTTP 200.
    if (call.name === 'web_fetch' && typeof meta?.url === 'string' && Number.isInteger(meta.statusCode)
      && Number(meta.statusCode) >= 100 && Number(meta.statusCode) <= 599 && typeof meta.truncated === 'boolean') {
      try {
        const url = new URL(meta.url)
        if (url.protocol === 'http:' || url.protocol === 'https:') {
          records.push({ ...identity, kind: 'http', detail: `${url.origin}${url.pathname.slice(0, 300)} · HTTP ${meta.statusCode}${meta.truncated ? ' · truncated' : ''}` })
        }
      } catch { /* Malformed metadata is not evidence. */ }
    }
    if (Array.isArray(node.content)) {
      const images = node.content.filter(block => {
        const image = object(block)
        const attachment = object(image?.attachment)
        return image?.type === 'image' && attachment !== undefined && typeof attachment.mediaType === 'string'
          && ['image/png', 'image/jpeg', 'image/webp', 'image/gif'].includes(attachment.mediaType)
      })
      if (images.length) records.push({ ...identity, kind: 'image', detail: String(images.length) })
    }
  }
  return [...new Map(records.map(record => [JSON.stringify([record.eventSeq, record.callId, record.kind]), record])).values()]
}

export function NativeToolEvidence({ nodes, en, variant = 'task-row' }: { readonly nodes: readonly unknown[]; readonly en: boolean; readonly variant?: 'task-row' | 'activity' }) {
  const records = nativeToolObservations(nodes)
  if (variant === 'activity') {
    if (records.length === 0) return null
    return <details className="yuqi-activity-file-evidence-foldout">
      <summary>{en ? `Network requests & image records (${records.length})` : `网络请求与图片记录（${records.length}）`}</summary>
      <p>{en ? 'Only successful native web_fetch metadata and image result blocks recorded for this task are shown here.' : '仅展示此任务已记录的成功原生 web_fetch 元数据与图片结果块。'}</p>
      <ul>{records.map(record => <li key={`${record.eventSeq}:${record.callId}:${record.kind}`}>
        <strong>{record.kind === 'http' ? (en ? record.detail : record.detail.replace(/ · truncated$/u, ' · 内容已截断')) : `${en ? 'Image results' : '图片结果'}: ${record.detail}`}</strong>
        <p>{record.tool} · {en ? 'event' : '事件'} #{record.eventSeq} · {record.callId}</p>
      </li>)}</ul>
    </details>
  }
  return <section className="yuqi-insight-section" aria-label={en ? 'Browser & HTTP tool records' : '网络请求与图片记录'}>
    <h4>{en ? 'Browser & HTTP Requests' : '网络请求与图片记录'}</h4>
    <p>{en ? 'Records native web requests and images generated by this task.' : '记录子代理在执行过程中产生的网络请求（web_fetch）与图片产物。'}</p>
    {records.length === 0 ? <p>{en ? 'No network requests or image records for this task.' : '当前任务暂无网络请求或图片记录。'}</p>
      : <ul>{records.map(record => <li key={`${record.eventSeq}:${record.callId}:${record.kind}`}>
        <strong>{record.kind === 'http' ? (en ? record.detail : record.detail.replace(/ · truncated$/u, ' · 内容已截断')) : `${en ? 'Image results' : '图片结果'}: ${record.detail}`}</strong>
        <p>{record.tool} · {en ? 'event' : '事件'} #{record.eventSeq} · {record.callId}</p>
        <span>{en ? 'Recorded' : '已记录'}</span>
      </li>)}</ul>}
  </section>
}
